name: Deploy COBOL Website to SiteGround

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: almalinux:8

    steps:
      - name: Install required packages
        run: |
          dnf install -y epel-release
          dnf groupinstall -y "Development Tools"
          dnf install -y \
            gcc make wget tar \
            gmp-devel libxml2-devel ncurses-devel db4-devel \
            which

      - name: Download and build GNUCobol
        run: |
          wget https://ftp.gnu.org/gnu/gnucobol/gnucobol-3.2.tar.gz
          tar xzf gnucobol-3.2.tar.gz
          cd gnucobol-3.2
          ./configure
          make -j$(nproc)
          make install
          ldconfig

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Compile COBOL program
        run: |
          mkdir -p build dist
          cobc -x -o build/hello-world src/hello_world.cbl
          file build/hello-world
          build/hello-world
          cp build/hello-world dist/

      - name: Deploy binary via rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avrh --delete
          path: dist/
          remote_path: /home/${{ vars.SSH_USERNAME }}/www/wpaz.dev/public_html/cobolTest/
          remote_host: ${{ vars.SSH_HOST }}
          remote_port: 18765
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
