name: Deploy This Website to Siteground
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v4

      - uses: fabasoad/setup-cobol-action@v1
      - name: Run script
        run: |
          mkdir dist
          mkdir build
          cobc -x -static -o build/hello-world src/hello_world.cbl
          ls -al build/
          build/hello-world
          cp build/hello-world dist/
          ls -al dist
      - name: Deploy using Rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avrh --delete
          path: dist/
          remote_path: /home/${{ vars.SSH_USERNAME }}/www/wpaz.dev/public_html/cobolTest/
          remote_host: ${{ vars.SSH_HOST }}
          remote_port: 18765 
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
