name: Deploy COBOL Website to SiteGround

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up GNU COBOL
        uses: fabasoad/setup-cobol-action@v1

      - name: Build and Copy COBOL App
        run: |
          mkdir -p dist/lib
          mkdir -p build

          # Optional static compile (fails silently if unsupported)
          cobc -C -o build/hello-world.c src/hello_world.cbl
          gcc -static -o build/hello-world build/hello-world.c -lcob -lncurses -lxml2 -lgmp -ldb || echo "Static linking failed, falling back to dynamic link"

          # Fallback to dynamic link
          cobc -x -o build/hello-world src/hello_world.cbl

          # Show info
          file build/hello-world
          ./build/hello-world

          # Copy executable
          cp build/hello-world dist/

          # Copy only required shared libraries
          ldd build/hello-world | awk '{ print $3 }' | grep ^/ | xargs -I '{}' cp -v '{}' dist/lib/

          # Show contents
          ls -al dist/
          ls -al dist/lib/

      - name: Upload Required Libraries
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avrh --delete
          path: dist/lib/
          remote_path: /home/${{ vars.SSH_USERNAME }}/lib/
          remote_host: ${{ vars.SSH_HOST }}
          remote_port: 18765
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload COBOL Executable
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avrh --delete
          path: dist/
          remote_path: /home/${{ vars.SSH_USERNAME }}/www/wpaz.dev/public_html/cobolTest/
          remote_host: ${{ vars.SSH_HOST }}
          remote_port: 18765
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
