name: Deploy This Website to Siteground
on:
  push:
    branches: [main,dev]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: misterfalcon/fedora-gnucobol:latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v4
      - name: Copy files to dist
        run: |
          scripts/build.sh
      - name: Set remote path
        id: set_path
        run: |
          echo "Current branch is: ${{ github.ref_name }}"
         
          if [ "${{ github.ref_name }}" = "main" ]; then
            REMOTE_PATH="wpaz.dev"
          else
            REMOTE_PATH="dev.wpaz.dev"
          fi

          echo "REMOTE_PATH=$REMOTE_PATH" >> $GITHUB_ENV
          echo "Remote path: $REMOTE_PATH"
          
      - name: Deploy binary via rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -rlpcgoDv --delete
          path: dist/
          remote_path: /home/${{ vars.SSH_USERNAME }}/www/${{ env.REMOTE_PATH }}/public_html/cobolTest/
          remote_host: ${{ vars.SSH_HOST }}
          remote_port: ${{ vars.SSH_PORT }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
